spring:
  cloud:
    gateway:
      routes:
        - id: bd_route
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu
        - id: qq_route
          uri: https://www.qq.com
          predicates:
            - Query=url,qq
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: xmall-gateway
#  main:
#    web-application-type: reactive
server:
  port: 88